junction/pages/urls.py
# -*- coding: utf-8 -*-

# Third Party Stuff
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns(
    '',
    url(r'^$', views.HomePageView.as_view(), name="homepage"),
)

junction/profiles/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
]

junction/tickets/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

# Third Party Stuff
from django.conf.urls import patterns, url

# Junction Stuff
from . import views

urlpatterns = patterns(
    '',
    url(r'^sync_data/$', views.sync_data, name='sync_data'),
)

junction/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

# Third Party Stuff
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import RedirectView, TemplateView

from rest_framework import routers
from junction.schedule import views as schedule_views
from junction.conferences import views as conference_views
from junction.devices.views import DeviceListApiView, DeviceDetailApiView
from junction.feedback.views import (FeedbackQuestionListApiView,
                                     FeedbackListApiView, view_feedback)
from junction.schedule.views import non_proposal_schedule_item_view


router = routers.DefaultRouter()

router.register('conferences', conference_views.ConferenceView)
router.register('venues', conference_views.VenueView)
router.register('rooms', conference_views.RoomView)

router.register('schedules', schedule_views.ScheduleView)

'''
Root url routering file.

You should put the url config in their respective app putting only a
reference to them here.
'''

urlpatterns = patterns(
    '',

    # Django Admin
    url(r'^nimda/', include(admin.site.urls)),

    # Third Party Stuff
    url(r'^accounts/', include('allauth.urls')),
    url('^markdown/', include('django_markdown.urls')),

    # Tickets
    url(r'^tickets/', include('junction.tickets.urls')),

    # Proposals related
    url(r'^(?P<conference_slug>[\w-]+)/proposals/', include('junction.proposals.urls')),
    url(r'^(?P<conference_slug>[\w-]+)/dashboard/reviewers/',
        'junction.proposals.dashboard.reviewer_comments_dashboard',
        name='proposal-reviewers-dashboard'),
    url(r'^(?P<conference_slug>[\w-]+)/dashboard/$',
        'junction.proposals.dashboard.proposals_dashboard', name='proposal-dashboard'),
    url(r'^(?P<conference_slug>[\w-]+)/dashboard/votes/$',
        'junction.proposals.dashboard.reviewer_votes_dashboard',
        name='proposal-reviewer-votes-dashboard'),
    url(r'^(?P<conference_slug>[\w-]+)/dashboard/votes/export/$',
        'junction.proposals.dashboard.export_reviewer_votes',
        name='export-reviewer-votes'),
    url(r'^feedback/(?P<schedule_item_id>\d+)/$',
        view_feedback,
        name='feedback-detail'),
    url(r'^schedule_item/(?P<sch_item_id>\d+)/$',
        non_proposal_schedule_item_view,
        name="schedule-item"),
    url(r'^api/v1/', include(router.urls)),
    # Device
    url(r'^api/v1/devices/$', DeviceListApiView.as_view(), name='device-list'),
    url(r'^api/v1/devices/(?P<_uuid>[\w-]+)/$', DeviceDetailApiView.as_view(),
        name='device-detail'),
    # Feedback
    url('^api/v1/feedback_questions/$',
        FeedbackQuestionListApiView.as_view(),
        name='feedback-questions-list'),
    url('^api/v1/feedback/$',
        FeedbackListApiView.as_view(),
        name='feedback-list'),
    # User Dashboard
    url(r'^profiles/', include('junction.profiles.urls', namespace="profiles")),

    # Schedule related
    url(r'^(?P<conference_slug>[\w-]+)/schedule/',
        include('junction.schedule.urls')),
    # Static Pages. TODO: to be refactored
    url(r'^speakers/$', TemplateView.as_view(template_name='static-content/speakers.html',), name='speakers-static'),
    url(r'^schedule/$', TemplateView.as_view(template_name='static-content/schedule.html',), name='schedule-static'),
    url(r'^venue/$', TemplateView.as_view(template_name='static-content/venue.html',), name='venue-static'),
    url(r'^sponsors/$', TemplateView.as_view(template_name='static-content/sponsors.html',), name='sponsors-static'),
    url(r'^blog/$', TemplateView.as_view(template_name='static-content/blog-archive.html',), name='blog-archive'),
    url(r'^coc/$', TemplateView.as_view(template_name='static-content/coc.html',), name='coc-static'),
    url(r'^faq/$', TemplateView.as_view(template_name='static-content/faq.html',), name='faq-static'),

    # Proposals as conference home page. TODO: Needs to be enhanced
    url(r'^(?P<conference_slug>[\w-]+)--/',
        RedirectView.as_view(pattern_name="proposals-list"),
        name='conference-detail'),

    # add at the last for minor performance gain
    url(r'^', include('junction.pages.urls', namespace='pages')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^400/$', 'django.views.defaults.bad_request'),  # noqa
        url(r'^403/$', 'django.views.defaults.permission_denied'),
        url(r'^404/$', 'django.views.defaults.page_not_found'),
        url(r'^500/$', 'django.views.defaults.server_error'),
    )

junction/conferences/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

# Third Party Stuff
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.timezone import now
from django.utils.translation import ugettext as _
from django_extensions.db.fields import AutoSlugField
from slugify import slugify
from uuid_upload_path import upload_to
from simple_history.models import HistoricalRecords

# Junction Stuff
from junction.base.constants import ConferenceStatus
from junction.base.models import AuditModel


@python_2_unicode_compatible
class Conference(AuditModel):

    """ Conference/Event master """
    name = models.CharField(max_length=255, verbose_name="Conference Name")
    slug = AutoSlugField(max_length=255, unique=True, populate_from=('name',), editable=True)
    description = models.TextField(default="")
    start_date = models.DateField(verbose_name="Start Date")
    end_date = models.DateField(verbose_name="End Date")
    logo = models.ImageField(blank=True, null=True, upload_to=upload_to)
    status = models.PositiveSmallIntegerField(
        choices=ConferenceStatus.CHOICES, verbose_name="Current Status")
    venue = models.ForeignKey('ConferenceVenue', null=True)

    deleted = models.BooleanField(default=False, verbose_name="Is Deleted?")

    class Meta:
        verbose_name = _('Conference')
        verbose_name_plural = _('Conferences')
        ordering = ('-start_date', 'name',)
        get_latest_by = 'start_date'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("conference-detail", kwargs={'conference_slug': self.slug})

    def clean(self):
        if self.end_date < self.start_date:
            msg = _("End date should be greater than start date.")
            raise ValidationError({'end_date': msg})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super(Conference, self).save(*args, **kwargs)

    def is_accepting_proposals(self):
        """Check if any one of the proposal section is accepting proposal.
        """
        return self.proposal_types.filter(end_date__gt=now()).exists()


@python_2_unicode_compatible
class ConferenceModerator(AuditModel):

    """ List of Conference Moderators/Administrators  """
    conference = models.ForeignKey(Conference, related_name='moderators')
    moderator = models.ForeignKey(User)
    active = models.BooleanField(default=True, verbose_name="Is Active?")

    class Meta:
        unique_together = ("conference", "moderator")
        verbose_name = 'moderator'
        verbose_name_plural = 'moderators'

    def __str__(self):
        return "{}[{}]".format(self.moderator.get_full_name(), self.conference)


@python_2_unicode_compatible
class ConferenceProposalReviewer(AuditModel):

    """ List of global proposal reviewers """
    conference = models.ForeignKey(Conference, related_name='proposal_reviewers')
    reviewer = models.ForeignKey(User)
    active = models.BooleanField(default=True, verbose_name="Is Active?")
    nick = models.CharField(max_length=255, verbose_name="Nick Name", default="Reviewer")
    history = HistoricalRecords()

    class Meta:
        verbose_name = 'proposals reviewer'
        verbose_name_plural = 'proposals reviewers'
        unique_together = ("conference", "reviewer")

    def __str__(self):
        return "{}[{}]".format(self.reviewer.get_full_name(), self.conference)


@python_2_unicode_compatible
class ConferenceVenue(AuditModel):
    name = models.CharField(max_length=100)

    address = models.TextField()

    latitude = models.DecimalField(max_digits=17, decimal_places=15)
    longitudes = models.DecimalField(max_digits=19, decimal_places=16)

    def __str__(self):
        return self.name


class Room(AuditModel):
    name = models.CharField(max_length=100)
    venue = models.ForeignKey(ConferenceVenue)

    note = models.CharField(max_length=255)

    def __str__(self):
        return "{}, {}".format(self.name, self.venue)

junction/proposals/forms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

# Third Party Stuff
from django import forms
from django.utils.safestring import mark_safe
from django.utils.timezone import now
from pagedown.widgets import PagedownWidget

# Junction Stuff
from junction.base.constants import (
    ProposalReviewStatus,
    ProposalStatus,
    ProposalTargetAudience,
    ProposalReviewerComment,
    ProposalVotesFilter,
)
from junction.proposals.models import (
    ProposalSection,
    ProposalType,
    ProposalSectionReviewerVoteValue
)


def _get_proposal_section_choices(conference, action="edit"):
    if action == "create":
        return [(str(cps.id), cps.name)
                for cps in ProposalSection.objects.filter(
                    conferences=conference)]
    else:
        return [(str(cps.id), cps.name)
                for cps in ProposalSection.objects.filter(
                    conferences=conference)]


def _get_proposal_type_choices(conference, action='edit'):
    if action == "create":
        return [(str(cpt.id), cpt.name)
                for cpt in ProposalType.objects.filter(
                    conferences=conference, end_date__gt=now())]
    else:
        return [(str(cpt.id), cpt.name)
                for cpt in ProposalType.objects.filter(
                    conferences=conference)]


def _get_proposal_section_reviewer_vote_choices():
    return [(i.vote_value, '{} ({})'.format(i.description, i.vote_value))
            for i in ProposalSectionReviewerVoteValue.objects.all()]


class HorizRadioRenderer(forms.RadioSelect.renderer):

    """
    This overrides widget method to put radio buttons horizontally instead of vertically.
    """

    def render(self):
        """Outputs radios"""
        return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))


class ProposalForm(forms.Form):

    '''
    Used for create/edit
    '''
    title = forms.CharField(min_length=10,
                            help_text="Title of the proposal, no buzz words!",
                            widget=forms.TextInput(attrs={'class': 'charfield'}))
    description = forms.CharField(widget=PagedownWidget(show_preview=True),
                                  help_text=("Describe your proposal with clear objective in simple sentence."
                                             " Keep it short and simple."))
    target_audience = forms.ChoiceField(
        choices=ProposalTargetAudience.CHOICES,
        widget=forms.Select(attrs={'class': 'dropdown'}))
    status = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'dropdown'}),
        choices=ProposalStatus.CHOICES,
        help_text=("If you choose DRAFT people can't the see the session in the list."
                   " Make the proposal PUBLIC when you're done with editing the session."))
    proposal_type = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'dropdown'}))
    proposal_section = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'dropdown'}))

    # Additional Content
    prerequisites = forms.CharField(
        widget=PagedownWidget(show_preview=True), required=False,
        help_text="What should the participants know before attending your session?")
    content_urls = forms.CharField(
        widget=PagedownWidget(show_preview=True), required=False,
        help_text="Links to your session like GitHub repo, Blog, Slideshare etc ...")
    speaker_info = forms.CharField(
        widget=PagedownWidget(show_preview=True), required=False,
        help_text="Say something about yourself, work etc...")
    speaker_links = forms.CharField(
        widget=PagedownWidget(show_preview=True), required=False,
        help_text="Links to your previous work like Blog, Open Source Contributions etc ...")

    def __init__(self, conference, action="edit", *args, **kwargs):
        super(ProposalForm, self).__init__(*args, **kwargs)
        self.fields['proposal_section'].choices = _get_proposal_section_choices(
            conference, action=action)
        self.fields['proposal_type'].choices = _get_proposal_type_choices(
            conference, action=action)

    @classmethod
    def populate_form_for_update(self, proposal):
        form = ProposalForm(proposal.conference,
                            initial={'title': proposal.title,
                                     'description': proposal.description,
                                     'target_audience': proposal.target_audience,
                                     'prerequisites': proposal.prerequisites,
                                     'content_urls': proposal.content_urls,
                                     'speaker_info': proposal.speaker_info,
                                     'speaker_links': proposal.speaker_links,
                                     'status': proposal.status,
                                     'proposal_section': proposal.proposal_section.pk,
                                     'proposal_type': proposal.proposal_type.pk, })
        return form


class ProposalCommentForm(forms.Form):

    '''
    Used to add comments
    '''
    comment = forms.CharField(widget=PagedownWidget(show_preview=True))
    private = forms.BooleanField(required=False, widget=forms.HiddenInput())
    reviewer = forms.BooleanField(required=False, widget=forms.HiddenInput())


class ProposalReviewForm(forms.Form):

    """
    Used to review the proposal.
    """
    review_status = forms.ChoiceField(
        choices=ProposalReviewStatus.CHOICES,
        widget=forms.RadioSelect()
    )


class ProposalReviewerVoteForm(forms.Form):

    """
    Used by ProposalSectionReviewers to vote on proposals.
    """
    vote_value = forms.ChoiceField(widget=forms.RadioSelect())
    comment = forms.CharField(
        widget=forms.Textarea,
        required=False,
        help_text="Leave a comment justifying your vote.",
    )

    def __init_(self):
        choices = _get_proposal_section_reviewer_vote_choices()
        self.fields['vote_value'].choices = choices


class ProposalTypesChoices(forms.Form):
    """
    Base proposal form with proposal sections & types.
    """
    proposal_section = forms.ChoiceField(widget=forms.Select(attrs={'class': 'dropdown'}))
    proposal_type = forms.ChoiceField(widget=forms.Select(attrs={'class': 'dropdown'}))

    def __init__(self, conference, *args, **kwargs):
        super(ProposalTypesChoices, self).__init__(*args, **kwargs)
        self.fields['proposal_section'].choices = _get_proposal_section_choices(conference)
        self.fields['proposal_type'].choices = _get_proposal_type_choices(conference)


class ProposalsToReviewForm(ProposalTypesChoices):
    """
    Used to filter proposals
    """
    reviewer_comment = forms.ChoiceField(widget=forms.Select(attrs={'class': 'dropdown'}))

    def __init__(self, conference, *args, **kwargs):
        super(ProposalsToReviewForm, self).__init__(conference, *args, **kwargs)
        self.fields['reviewer_comment'].choices = ProposalReviewerComment.CHOICES


class ProposalVotesFilterForm(ProposalTypesChoices):
    """
    Form  to filter proposals based on votes and review_status.
    """
    votes = forms.ChoiceField(widget=forms.Select(attrs={'class': 'dropdown votes'}))
    review_status = forms.ChoiceField(widget=forms.Select(attrs={'class': 'dropdown'}))

    def __init__(self, conference, *args, **kwargs):
        super(ProposalVotesFilterForm, self).__init__(conference, *args, **kwargs)
        self.fields['votes'].choices = ProposalVotesFilter.CHOICES
        self.fields['review_status'].choices = ProposalReviewStatus.CHOICES

        for name, field in self.fields.items():
            field.choices.insert(0, ('all', 'All'))

junction/pages/views.py
# -*- coding: utf-8 -*-

# Third Party Stuff
from django.views.generic import TemplateView

# Junction Stuff
from junction.conferences.models import Conference


class HomePageView(TemplateView):
    template_name = "pages/home_page.html"

    def get_conferences(self):
        qs = Conference.objects.all()
        return qs

    def get_context_data(self, **kwargs):
        kwargs['conferences'] = self.get_conferences()
        return super(HomePageView, self).get_context_data(**kwargs)

junction/templates/proposals/list.html
{% extends 'base.html' %}

{% load django_markdown %}
{% load static from staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block head_title %} {{ conference.name }} proposals {% endblock %}
{% block og_title %} {{ conference.name }} proposals {% endblock %}
{% block og_description %} {{ conference.description|markdown|safe|striptags}} {% endblock %}
{% block page_description %} {{ conference.description|markdown|safe|striptags}} {% endblock %}

{% block endhead %}
    <!-- Custom CSS -->
    <link href="{% static 'css/list.css' %}" rel="stylesheet">
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb conference.name "conference-detail" conference.slug %}
    {% breadcrumb "Proposals" "proposals-list" conference.slug %}
{% endblock %}

{% block navbar_logo %}
    {% if conference.logo %}
    <a href="{% url "conference-detail" conference.slug %}">
        <img src="{{ conference.logo.url }}">
    </a>
    {% else %}
        <a href="#" class="navbar-brand">{{ conference.name }}</a>
    {% endif %}
{% endblock navbar_logo %}

{% block page_classes %}{{ block.super}} page-proposals{% endblock page_classes %}

{% block content %}
<section class="content custom-container proposal-list">
    <div class="push-4-bottom push-1-top">
        <div class="row">
            <div class="col-xs -12 col-sm-12 ">
                <p class="meta">
                    <b class="text-muted">
                        <span class="start_date">{{ conference.start_date }}</span> –
                        <span class="end_date">{{ conference.end_date }}</span>
                    </b>
                    {% if is_proposal_reviewer %}
                        <a class='btn btn-primary pull-right' href="{% url 'proposal-dashboard' conference.slug %}">
                            Reviewer Dashboard
                        </a>
                    {% endif %}
                    <span class="status status-{{conference.status}}">
                        {{ conference.get_status_display }}
                    </span>
                </p>
                <hr>
                <p class="text-left">{{ conference.description|markdown }}</p>
                {% if is_reviewer %}
                    <a class='btn btn-primary' href="{% url 'proposals-to-review' conference.slug %}">Proposals To Review</a>
                {% endif %}
                {% if user.is_superuser or user.is_stuff %}
                    <a class='btn btn-primary' href="{% url 'proposal-reviewer-votes-dashboard' conference.slug %}">
                        Reviewer Votes Dashboard
                    </a>
                {% endif %}

            </div>
        </div>
        <div class="row">
            <div class="col-xs -12 col-sm-12 ">
                <h2>Proposal Sections</h2>
                <ol>
                {% for section in proposal_sections %}
                 <li><b>{{section.name}}</b> - {{section.description}}</li>
                {% endfor %}
                </ol>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-xs -12 col-sm-12 ">
                <h2>Proposal Types</h2>
                <ol>
                {% for types in proposal_types %}
                 <li><b>{{types.name}}</b> - {{types.description}}</li>
                {% endfor %}
                </ol>
            <hr>
            </div>
        </div>

        {% if user.is_authenticated %}
            <a class='btn btn-primary' href="{% url 'profiles:dashboard' %}">My Proposals</a>
        {% endif %}

        <a name="proposals"></a>
        <div class="row">
        {% if is_filtered %}
            <a class='btn btn-info pull-left' href="./"> <i class="fa fa-list"></i> View all proposals <i class="fa fa-close"></i></a>
        {% endif %}
        {% if conference.is_accepting_proposals %}
            <a class='btn btn-primary pull-right' href="{% url 'proposal-create' conference.slug %}">
                <i class="fa fa-plus-square-o"></i> New Proposal
            </a>
        {% endif %}
        </div>
        {% if selected_proposals %}
            {% include 'proposals/partials/proposal-list--selected-items.html' with proposals=selected_proposals title="Selected Proposals" display_status=False %}
        {% endif %}


        {% if public_proposals_list %}
            {% include 'proposals/partials/proposal-list--items.html' with proposals=public_proposals_list title="List of Proposals" display_status=False %}
        {% else %}
            <hr>
            <h2>List of Proposals</h2>
            <p>No proposals. </p>
        {% endif %}

    </div>
</section>
{% endblock %}

junction/templates/proposals/reviewers_dashboard.html
{% extends 'base.html' %}

{% load django_markdown %}
{% load static from staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block head_title %} {{ conference.name }} Reviewers dashbaord {% endblock %}
{% block og_title %} {{ conference.name }} Reviewers dashboard {% endblock %}
{% block og_description %} {{ conference.description|markdown|safe|striptags}} {% endblock %}
{% block page_description %} {{ conference.description|markdown|safe|striptags}} {% endblock %}

{% block endhead %}
    <!-- Custom CSS -->
    <link href="{% static 'css/list.css' %}" rel="stylesheet">
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb conference.name "conference-detail" conference.slug %}
    {% breadcrumb "Dashboard" "proposals-dashoboard" conference.slug %}
{% endblock %}


{% block navbar_logo %}
    {% if conference.logo %}
    <a href="{% url "conference-detail" conference.slug %}">
        <img src="{{ conference.logo.url }}">
    </a>
    {% else %}
        <a href="#" class="navbar-brand">{{ conference.name }}</a>
    {% endif %}
{% endblock navbar_logo %}

{% block page_classes %}{{ block.super}} page-proposals{% endblock page_classes %}

{% block content %}
<section class="content custom-container proposal-list">
    <div class="push-4-bottom push-1-top">
        <div class="row">
            <div class="col-xs -12 col-sm-12 ">
                <p class="meta">
                    <b class="text-muted">
                        <span class="start_date">{{ conference.start_date }}</span> –
                        <span class="end_date">{{ conference.end_date }}</span>
                    </b>
                    {% if is_proposal_reviewer %}
                        <a class='btn btn-primary pull-right' href="{% url 'proposal-dashboard' conference.slug %}">
                            Reviewer Dashboard
                        </a>
                    {% endif %}
                    <span class="status status-{{conference.status}}">
                        {{ conference.get_status_display }}
                    </span>
                </p>
                <hr>
                <p class="text-left">{{ conference.description|markdown }}</p>
            </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs -6 col-sm-6 ">
                <div class="panel panel-primary">
                    <div class="panel-heading"> By Reviewers</div>
                    <div class="panel-body">
                        <table border=1>
                            <tr>
                                <th>Reviewers</th>
                                <th>Proposal Reviewed</th>
                            </tr>
                            {% for id, data  in by_conference.items %}
                            <tr>

                                <td>{{data.0.first_name}} {{data.0.last_name}}</td>
                                <td>{{data.1}}</td>

                            </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>


        </div>
        <div class="row">
        <div class="col-xs -8 col-sm-8 ">
                <div class="panel panel-primary">
                    <div class="panel-heading">Reviewer/Section </div>
                    <div class="panel-body">
                     <table border=1>
                            <tr>
                                <th>Reviewers</th>
                                <th>Section Based Stat</th>
                            </tr>
                            {% for id,section in by_section.items %}
                             <tr>
                                <td>
                                {{section.reviewer.first_name}} {{section.reviewer.last_name}}
                                </td>
                                <td>
                                <table border=1>
                                 <tr>
                                        <td>Section </td>
                                        <td>Total</td>
                                        <td>Reviewed</td>
                                        <td>Yet to be reviewed</td>
                                 </tr>
                                {% for values  in section.interaction %}
                                <tr>
                                 <td width="250">{{values.3}}</td>
                                 <td width="50">{{values.0}}</td>
                                 <td>{{values.1}}</td>
                                 <td>{{values.2}}</td>
                                 </tr>
                                {% endfor %}

                                </table>
                                </td>
                            </tr>
                            {% endfor %}
                        </table>

                    </div>
                </div>
            </div>
        </div>


    </div>
</section>
{% endblock %}

junction/templates/proposals/to_review.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% load django_markdown %}
{% load static from staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block head_title %} {{ conference.name }} proposals to review {% endblock %}
{% block og_title %} {{ conference.name }} proposals to review {% endblock %}
{% block og_description %} {{ conference.description|markdown|safe|striptags}} {% endblock %}
{% block page_description %} {{ conference.description|markdown|safe|striptags}} {% endblock %}

{% block endhead %}
    <!-- Custom CSS -->
    <link href="{% static 'css/list.css' %}" rel="stylesheet">
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb conference.name "conference-detail" conference.slug %}
    {% breadcrumb "Proposals To Review" "proposals-to-review" conference.slug %}
{% endblock %}

{% block navbar_logo %}
    {% if conference.logo %}
        <a href="{% url "conference-detail" conference.slug %}">
            <img src="{{ conference.logo.url }}">
        </a>
    {% else %}
        <a href="#" class="navbar-brand">{{ conference.name }}</a>
    {% endif %}
{% endblock navbar_logo %}

{% block page_classes %}{{ block.super}} page-proposals{% endblock page_classes %}

{% block content %}
    <section class="content custom-container proposal-list">
        <div class="push-4-bottom push-1-top">
            <a name="proposals"></a>
            {% if proposals_to_review %}
                <h2>Proposals To Review</h2>
                <hr>
                <div id="filter">
                    <form method="POST" action="" class="form-inline">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        {% buttons %}
                        <a class="btn-clear-filter" href="./" style='display: none; margin-left: 1em;'>
                            clear filters
                        </a>
                       {% endbuttons %}
                    </form>
                </div>

                <hr>
                <div id="#proposals">
                    {% for section_items in proposals_to_review  %}
                        {% include 'proposals/partials/proposal-list--review-items.html' with proposals=section_items.proposals title=section_items.section display_status=False %}
                    {% endfor %}
                </div>

            {% else %}
                <p>No proposals to review. </p>
            {% endif %}
        </div>
    </section>
{% endblock %}

{% block script_extra %}
    <script>
    $.each($('#filter select'), function(val, text) {
        $(this).prepend( new Option('All', 'All') );
        $(this).val('All').change();
    });

    $('#filter select').change(function(e){
        e.preventDefault();
        var filter = false;
        var p_section = $( "#id_proposal_section option:selected" ).text(),
            p_type = $( "#id_proposal_type option:selected" ).text(),
            r_comment = $( "#id_reviewer_comment" ).val();

        if (p_section != 'All') {
            $( ".proposal-section" ).show().not( '[id~="' + p_section + '"]' ).hide();
        }
        if (p_type != 'All') {
            $( ".proposal" ).show().not( '[data-type~="' + p_type + '"]' ).hide();
        }
        if (r_comment != 'All') {
            $( ".proposal" ).show().not( '[data-comment~="' + r_comment + '"]' ).hide();
        }
        if ( r_comment == 'All' && p_section == 'All' && p_type == 'All') {
            $('.btn-clear-filter').hide()
        } else {
            $('.btn-clear-filter').show()
        }
    });
    </script>
{% endblock %}